# Generated by Django 4.2.2 on 2023-07-23 05:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_author_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
