# Generated by Django 4.2.2 on 2023-08-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_project_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='project+thumb/'),
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.project')),
            ],
        ),
    ]
